# config details
config_name: "kafuegorge_lower_specs"

reservoir:
  # Total Storage Capacity (Dead + Live)
  operable_storage_max:  6179000000 
  
  # Minimum Operating Level (Dead Storage)
  operable_storage_min: 16000000  
  
  # Max discharge 
  max_safe_release: 4060 # To validate - atm 6x200 m3/s + 6x140 m3/s turbines + 9500 m3/s spillway
  
  sp_to_ep: [
    [
        0,              # Level 972.3m
        5000000,        # Level 972.5m
        11000000,       # Level 972.75m
        20000000,       # Level 973m
        29000000,    # Level 973.5m
        40000000,      # Level 974m
        53000000,
        69000000,
        88000000,
        111000000,
        138000000,
        170000000,
        211000000,
        263000000,
        331000000,
        423000000,
        548000000,
        709000000,
        785000000,
        915000000,
        1178000000,
        2845000000 # estimated max level 978m
    ],
    [
        972.3,
        972.5,
        972.75,
        973,
        973.25,
        973.5,
        973.75,
        974,
        974.25,
        974.5,
        974.75,
        975,
        975.25,
        975.5,
        975.75,
        976,
        976.25,
        976.5,
        976.6,
        976.75,
        977,
        978,
    ]
  ]
  # Day of water year to TOCS (Active Storage - m3)
  tp_to_tocs : [
    [
    ],
    [
    ]
  ]
  
  # Storage Height to max release (m3 to m3/s)
  sp_to_rp_max: [
    [
      950,
      972.5,
      972.9,
      973,
      973.5,
      974,
      974.5,
      975,
      975.5,
      976,
      976.6,
      977,
      977.5,
      978,
      978.5,
      979,
      979.5,
      980,
    ],
    [
      0,
      0,
      780,
      1076,
      1250.35,
      1420,
      1607.44,
      1804,
      2007.08,
      2220,
      2496,
      2668,
      2894.46,
      3132,
      3364,
      3596,
      3828,
      4060,
    ]
  ]
  # Storage Height to min release (m to m3/s)
  sp_to_rp_min: [
    [
      950,
      972.5,
      972.9,
      973,
      973.5,
      974,
      974.5,
      975,
      975.5,
      976,
      976.6,
      977,
      977.5,
      978,
      978.5,
      979,
      979.5,
      980,
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2894.46,
      3132,
      3364,
      3596,
      3828,
      4060,
    ]
  ]