# config details
config_name: "kariba_specs"

reservoir:
    turbines:
        north:
            capacity: 200 #m3/s
            efficiency: 0.48
            head: 128.9 #m
            quantity: 6

        south:
            capacity: 140 #m3/s
            efficiency: 0.51
            head: 128.9 #m
            quantity: 6

    # Total Storage Capacity (Dead + Live)
    operable_storage_max:  193000000000 
    
    # Minimum Operating Level (Dead Storage)
    operable_storage_min: 116000000000  
    
    # Max discharge 
    max_safe_release: 11539.94 # To validate - atm 6x200 m3/s + 6x140 m3/s turbines + 9500 m3/s spillway
    
    # Volume-Height curve (m3 to m)
    sp_to_ep: [
        [
            0,              # Level 453
            116000000000,   # Level 475.5 (1,16E+11)
            118000000000,   # Level 476   (1,18E+11)
            123000000000,   # Level 477   (1,23E+11)
            127000000000,   # Level 478   (1,27E+11)
            132000000000,   # Level 479   (1,32E+11)
            137000000000,   # Level 480   (1,37E+11)
            142000000000,   # Level 481   (1,42E+11)
            146000000000,   # Level 482   (1,46E+11)
            151000000000,   # Level 483   (1,51E+11)
            157000000000,   # Level 484   (1,57E+11)
            162000000000,   # Level 485   (1,62E+11)
            167000000000,   # Level 486   (1,67E+11)
            173000000000,   # Level 487   (1,73E+11)
            181000000000,   # Level 488.5 (1,81E+11)
            193000000000    # Level 489.5 (1,93E+11)
        ],
        [
            453,
            475.5,
            476,
            477,
            478,
            479,
            480,
            481,
            482,
            483,
            484,
            485,
            486,
            487,
            488.5,
            489.5
        ]
    ]
    # Volume-Area curve (m3 to m2)
    sp_to_aa: [
        [
            0,              # Level 453
            116000000000,   # Level 475.5 (1,16E+11)
            118000000000,   # Level 476   (1,18E+11)
            123000000000,   # Level 477   (1,23E+11)
            127000000000,   # Level 478   (1,27E+11)
            132000000000,   # Level 479   (1,32E+11)
            137000000000,   # Level 480   (1,37E+11)
            142000000000,   # Level 481   (1,42E+11)
            146000000000,   # Level 482   (1,46E+11)
            151000000000,   # Level 483   (1,51E+11)
            157000000000,   # Level 484   (1,57E+11)
            162000000000,   # Level 485   (1,62E+11)
            167000000000,   # Level 486   (1,67E+11)
            173000000000,   # Level 487   (1,73E+11)
            181000000000,   # Level 488.5 (1,81E+11)
            193000000000    # Level 489.5 (1,93E+11)
        ],
        [
            0,
            4354000000,
            4405000000,
            4507000000,
            4608000000,
            4709000000,
            4811000000,
            4901000000,
            4991000000,
            5081000000,
            5171000000,
            5261000000,
            5350000000,
            5440000000,
            5577000000,
            5671000000
        ]
    ]
    # Day of water year to TOCS (Active Storage - m3)
    tp_to_tocs : [
        [
            31,  # Month 1 end
            59,  # Month 2 end
            90,  # Month 3 end
            120, # Month 4 end
            151, # Month 5 end
            181, # Month 6 end
            212, # Month 7 end
            243, # Month 8 end
            273, # Month 9 end
            304, # Month 10 end
            334, # Month 11 end
            365  # Month 12 end
        ],
        [
            40666000000, # Month 1 Storage
            47696000000, # Month 2 Storage
            60221000000, # Month 3 Storage
            64798000000, # Month 4 Storage
            64798000000, # Month 5 Storage
            64798000000, # Month 6 Storage
            61662000000, # Month 7 Storage
            58808000000, # Month 8 Storage
            56054000000, # Month 9 Storage
            53788000000, # Month 10 Storage
            50769000000, # Month 11 Storage
            48204000000  # Month 12 Storage
        ]
    ]
    
    # Storage Height to max release (m to m3/s)
    sp_to_rp_max: [
        [
            950,
            972.5,
            972.9,
            973,
            973.5,
            974,
            974.5,
            975,
            975.5,
            976,
            976.6,
            977,
            977.5,
            978,
            978.5,
            979,
            979.5,
            980,
        ],
        [
            0,
            0,
            780,
            1076,
            1250.35,
            1420,
            1607.44,
            1804,
            2007.08,
            2220,
            2496,
            2668,
            2894.46,
            3132,
            3364,
            3596,
            3828,
            4060,
        ]
    ]

    # Storage Height to min release (m to m3/s)
    sp_to_rp_min: [
        [
            950,
            972.5,
            972.9,
            973,
            973.5,
            974,
            974.5,
            975,
            975.5,
            976,
            976.6,
            977,
            977.5,
            978,
            978.5,
            979,
            979.5,
            980,
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            2894.46,
            3132,
            3364,
            3596,
            3828,
            4060,
        ]
    ]